### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by anaraquelmendes** [anaraquelmendes/modularity-mindfulness#1]
Hi Charlie, 

Could you show me why my images are not as big as they should on larger screens?

Thanks

@charlie-quinn

**Comment by charlie-quinn** [comment]
Hey @anaraquelmendes have you pushed your latest version of this assignment? If so, I'd like to go over this one with you in class rather than on GitHub (will be easier to explain what's happening).

**Comment by anaraquelmendes** [comment]
Sure Charlie, thanks!
@charlie-quinn
